export interface MoleculeAtom {
    position: [number, number, number];
    type: string; // Atomic symbol (H, O, Na, Cl, etc.)
    scale?: number;
}

export interface MoleculeBond {
    start: [number, number, number];
    end: [number, number, number];
    type: 'covalent' | 'ionic' | 'hydrogen';
}

export interface MoleculePreset {
    id: string;
    name: string;
    formula: string;
    description: string;
    atoms: MoleculeAtom[];
    bonds: MoleculeBond[];
}

// Water Molecule (H2O)
// O at center, H at specific 104.5 degree angles
const hDist = 0.96; // Oxygen-Hydrogen bond length in Angstroms (scaled for view)
const angle = (104.5 * Math.PI) / 180;
const h1x = hDist * Math.sin(angle / 2);
const h1y = -hDist * Math.cos(angle / 2);
const h2x = -hDist * Math.sin(angle / 2);
const h2y = -hDist * Math.cos(angle / 2);

// Generate Buckyball (C60) coordinates using a truncated icosahedron formula
function generateBuckyball(): { atoms: MoleculeAtom[], bonds: MoleculeBond[] } {
    const phi = (1 + Math.sqrt(5)) / 2;
    const r = 2.0; // Scale radius
    const rawVertices: [number, number, number][] = [];

    // The 60 vertices of a truncated icosahedron can be generated by all even permutations of:
    // (0, ±1, ±3φ)
    const p1 = [
        [0, 1, 3 * phi], [0, 1, -3 * phi], [0, -1, 3 * phi], [0, -1, -3 * phi],
        [1, 3 * phi, 0], [1, -3 * phi, 0], [-1, 3 * phi, 0], [-1, -3 * phi, 0],
        [3 * phi, 0, 1], [3 * phi, 0, -1], [-3 * phi, 0, 1], [-3 * phi, 0, -1]
    ];
    // (±1, ±(2+φ), ±2φ)
    const p2 = [
        [1, 2 + phi, 2 * phi], [1, 2 + phi, -2 * phi], [1, -(2 + phi), 2 * phi], [1, -(2 + phi), -2 * phi],
        [-1, 2 + phi, 2 * phi], [-1, 2 + phi, -2 * phi], [-1, -(2 + phi), 2 * phi], [-1, -(2 + phi), -2 * phi],
        [2 + phi, 2 * phi, 1], [2 + phi, 2 * phi, -1], [2 + phi, -2 * phi, 1], [2 + phi, -2 * phi, -1],
        [-(2 + phi), 2 * phi, 1], [-(2 + phi), 2 * phi, -1], [-(2 + phi), -2 * phi, 1], [-(2 + phi), -2 * phi, -1],
        [2 * phi, 1, 2 + phi], [2 * phi, 1, -(2 + phi)], [2 * phi, -1, 2 + phi], [2 * phi, -1, -(2 + phi)],
        [-2 * phi, 1, 2 + phi], [-2 * phi, 1, -(2 + phi)], [-2 * phi, -1, 2 + phi], [-2 * phi, -1, -(2 + phi)]
    ];
    // (±φ, ±2, ±(2φ+1))
    const p3 = [
        [phi, 2, 2 * phi + 1], [phi, 2, -(2 * phi + 1)], [phi, -2, 2 * phi + 1], [phi, -2, -(2 * phi + 1)],
        [-phi, 2, 2 * phi + 1], [-phi, 2, -(2 * phi + 1)], [-phi, -2, 2 * phi + 1], [-phi, -2, -(2 * phi + 1)],
        [2, 2 * phi + 1, phi], [2, 2 * phi + 1, -phi], [2, -(2 * phi + 1), phi], [2, -(2 * phi + 1), -phi],
        [-2, 2 * phi + 1, phi], [-2, 2 * phi + 1, -phi], [-2, -(2 * phi + 1), phi], [-2, -(2 * phi + 1), -phi],
        [2 * phi + 1, phi, 2], [2 * phi + 1, phi, -2], [2 * phi + 1, -phi, 2], [2 * phi + 1, -phi, -2],
        [-(2 * phi + 1), phi, 2], [-(2 * phi + 1), phi, -2], [-(2 * phi + 1), -phi, 2], [-(2 * phi + 1), -phi, -2]
    ];

    const allP = [...p1, ...p2, ...p3];

    // Normalize and scale
    allP.forEach(p => {
        const len = Math.sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2]);
        rawVertices.push([p[0] / len * r, p[1] / len * r, p[2] / len * r]);
    });

    const atoms: MoleculeAtom[] = rawVertices.map(v => ({ position: v, type: 'C', scale: 0.25 }));
    const bonds: MoleculeBond[] = [];

    // Find edges by distance (C-C bonds in C60)
    // The closest neighbors should form the 90 edges of the truncated icosahedron
    const expectedDist = 2 * r * Math.sin(Math.PI / 10); // Approx distance between adjacent vertices
    const tolerance = 0.1;

    for (let i = 0; i < rawVertices.length; i++) {
        for (let j = i + 1; j < rawVertices.length; j++) {
            const dx = rawVertices[i][0] - rawVertices[j][0];
            const dy = rawVertices[i][1] - rawVertices[j][1];
            const dz = rawVertices[i][2] - rawVertices[j][2];
            const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
            if (Math.abs(dist - expectedDist) < tolerance) {
                bonds.push({ start: rawVertices[i], end: rawVertices[j], type: 'covalent' });
            }
        }
    }

    return { atoms, bonds };
}

const buckyballData = generateBuckyball();


export const MOLECULE_PRESETS: Record<string, MoleculePreset> = {
    water: {
        id: 'water',
        name: 'Water',
        formula: 'H₂O',
        description: 'The universal solvent. A polar molecule with unique hydrogen bonding capabilities.',
        atoms: [
            { position: [0, 0, 0], type: 'O', scale: 0.6 },
            { position: [h1x, h1y, 0], type: 'H', scale: 0.35 },
            { position: [h2x, h2y, 0], type: 'H', scale: 0.35 },
        ],
        bonds: [
            { start: [0, 0, 0], end: [h1x, h1y, 0], type: 'covalent' },
            { start: [0, 0, 0], end: [h2x, h2y, 0], type: 'covalent' },
        ]
    },
    nacl: {
        id: 'nacl',
        name: 'Sodium Chloride',
        formula: 'NaCl',
        description: 'Table salt. A classic example of an ionic crystal lattice.',
        atoms: [], // Populated dynamically in component for lattice
        bonds: []
    },
    diamond: {
        id: 'diamond',
        name: 'Diamond (Carbon)',
        formula: 'C (Allotrope)',
        description: 'A super-hard allotrope of carbon where every atom is covalently bonded to four others in a rigid tetrahedral lattice.',
        atoms: [], // Populated dynamically
        bonds: []
    },
    graphite: {
        id: 'graphite',
        name: 'Graphite (Carbon)',
        formula: 'C (Allotrope)',
        description: 'A soft, conductive allotrope of carbon consisting of stacked hexagonal sheets held together by weak Van der Waals forces.',
        atoms: [], // Populated dynamically
        bonds: []
    },
    caffeine: {
        id: 'caffeine',
        name: 'Caffeine',
        formula: 'C₈H₁₀N₄O₂',
        description: 'A central nervous system stimulant. A complex organic alkaloid molecule with intertwined rings.',
        // Approximate 3D coordinates for Caffeine (scaled)
        atoms: [
            { position: [-1.26, -0.42, 0.00], type: 'N', scale: 0.4 }, // N1
            { position: [-0.60, 0.81, 0.00], type: 'C', scale: 0.4 },  // C2
            { position: [-1.22, 1.88, 0.00], type: 'O', scale: 0.45 }, // O2
            { position: [0.77, 0.82, 0.00], type: 'N', scale: 0.4 },   // N3
            { position: [1.38, -0.37, 0.00], type: 'C', scale: 0.4 },  // C4
            { position: [0.65, -1.61, 0.00], type: 'C', scale: 0.4 },  // C5
            { position: [2.76, -0.44, 0.00], type: 'N', scale: 0.4 },  // N7
            { position: [2.89, -1.77, 0.00], type: 'C', scale: 0.4 },  // C8
            { position: [1.58, -2.48, 0.00], type: 'N', scale: 0.4 },  // N9
            { position: [-0.70, -1.60, 0.00], type: 'C', scale: 0.4 }, // C6
            { position: [-1.32, -2.66, 0.00], type: 'O', scale: 0.45 }, // O6
            { position: [-2.72, -0.36, 0.00], type: 'C', scale: 0.4 }, // C10 (Methyl)
            { position: [1.55, 2.06, 0.00], type: 'C', scale: 0.4 },   // C11 (Methyl)
            { position: [3.89, 0.48, 0.00], type: 'C', scale: 0.4 },   // C12 (Methyl)
            // Hydrogens omitted for visual clarity to keep the view focused on the complex ring structure,
            // or just add them near the methyl groups:
            { position: [-3.05, -0.87, 0.89], type: 'H', scale: 0.25 },
            { position: [-3.05, -0.87, -0.89], type: 'H', scale: 0.25 },
            { position: [-3.08, 0.67, 0.00], type: 'H', scale: 0.25 },
            { position: [1.88, 2.15, 1.03], type: 'H', scale: 0.25 },
            { position: [1.88, 2.15, -1.03], type: 'H', scale: 0.25 },
            { position: [0.91, 2.94, 0.00], type: 'H', scale: 0.25 },
            { position: [4.42, 0.29, 0.93], type: 'H', scale: 0.25 },
            { position: [4.42, 0.29, -0.93], type: 'H', scale: 0.25 },
            { position: [3.51, 1.50, 0.00], type: 'H', scale: 0.25 },
            { position: [3.79, -2.35, 0.00], type: 'H', scale: 0.25 }  // H on C8
        ],
        bonds: [
            // Six-membered ring
            { start: [-1.26, -0.42, 0.00], end: [-0.60, 0.81, 0.00], type: 'covalent' }, // N1-C2
            { start: [-0.60, 0.81, 0.00], end: [0.77, 0.82, 0.00], type: 'covalent' },   // C2-N3
            { start: [0.77, 0.82, 0.00], end: [1.38, -0.37, 0.00], type: 'covalent' },   // N3-C4
            { start: [1.38, -0.37, 0.00], end: [0.65, -1.61, 0.00], type: 'covalent' },  // C4-C5
            { start: [0.65, -1.61, 0.00], end: [-0.70, -1.60, 0.00], type: 'covalent' }, // C5-C6
            { start: [-0.70, -1.60, 0.00], end: [-1.26, -0.42, 0.00], type: 'covalent' },// C6-N1
            // Five-membered ring attached to C4-C5
            { start: [1.38, -0.37, 0.00], end: [2.76, -0.44, 0.00], type: 'covalent' },  // C4-N7
            { start: [2.76, -0.44, 0.00], end: [2.89, -1.77, 0.00], type: 'covalent' },  // N7-C8
            { start: [2.89, -1.77, 0.00], end: [1.58, -2.48, 0.00], type: 'covalent' },  // C8-N9
            { start: [1.58, -2.48, 0.00], end: [0.65, -1.61, 0.00], type: 'covalent' },  // N9-C5
            // Double bonded Oxygens
            { start: [-0.60, 0.81, 0.00], end: [-1.22, 1.88, 0.00], type: 'covalent' },  // C2=O2
            { start: [-0.70, -1.60, 0.00], end: [-1.32, -2.66, 0.00], type: 'covalent' },// C6=O6
            // Methyl groups
            { start: [-1.26, -0.42, 0.00], end: [-2.72, -0.36, 0.00], type: 'covalent' },// N1-C10
            { start: [0.77, 0.82, 0.00], end: [1.55, 2.06, 0.00], type: 'covalent' },    // N3-C11
            { start: [2.76, -0.44, 0.00], end: [3.89, 0.48, 0.00], type: 'covalent' },   // N7-C12
            // Methyl Hydrogens (C10)
            { start: [-2.72, -0.36, 0.00], end: [-3.05, -0.87, 0.89], type: 'covalent' },
            { start: [-2.72, -0.36, 0.00], end: [-3.05, -0.87, -0.89], type: 'covalent' },
            { start: [-2.72, -0.36, 0.00], end: [-3.08, 0.67, 0.00], type: 'covalent' },
            // Methyl Hydrogens (C11)
            { start: [1.55, 2.06, 0.00], end: [1.88, 2.15, 1.03], type: 'covalent' },
            { start: [1.55, 2.06, 0.00], end: [1.88, 2.15, -1.03], type: 'covalent' },
            { start: [1.55, 2.06, 0.00], end: [0.91, 2.94, 0.00], type: 'covalent' },
            // Methyl Hydrogens (C12)
            { start: [3.89, 0.48, 0.00], end: [4.42, 0.29, 0.93], type: 'covalent' },
            { start: [3.89, 0.48, 0.00], end: [4.42, 0.29, -0.93], type: 'covalent' },
            { start: [3.89, 0.48, 0.00], end: [3.51, 1.50, 0.00], type: 'covalent' },
            // H on C8
            { start: [2.89, -1.77, 0.00], end: [3.79, -2.35, 0.00], type: 'covalent' }
        ]
    },
    buckyball: {
        id: 'buckyball',
        name: 'Buckminsterfullerene (C60)',
        formula: 'C₆₀',
        description: 'A spherical fullerene consisting of 60 carbon atoms arranged in 20 hexagons and 12 pentagons. Resembles a soccer ball.',
        atoms: buckyballData.atoms,
        bonds: buckyballData.bonds
    },
    gold: {
        id: 'gold',
        name: 'Solid Gold (FCC Crystal)',
        formula: 'Au',
        description: 'A highly highly malleable transition metal. In its solid form, it creates a Face-Centered Cubic (FCC) crystal lattice held together by strong metallic bonds.',
        atoms: [], // Populated dynamically by CrystalLattice
        bonds: []
    },
    penicillin: {
        id: 'penicillin',
        name: 'Penicillin G',
        formula: 'C₁₆H₁₈N₂O₄S',
        description: 'A revolutionary antibiotic. Features a highly strained beta-lactam ring fused to a thiazolidine ring, allowing it to inhibit bacterial cell wall synthesis.',
        atoms: [], // Populated dynamically
        bonds: []
    },
    dna_segment: {
        id: 'dna_segment',
        name: 'DNA Double Helix',
        formula: 'Macromolecule',
        description: 'A segment of Deoxyribonucleic Acid (DNA). Features a twin sugar-phosphate backbone connected by hydrogen-bonded nucleotide bases (A-T, C-G).',
        atoms: [], // Populated procedurally
        bonds: []
    },
    methane: {
        id: 'methane',
        name: 'Methane',
        formula: 'CH₄',
        description: 'The simplest hydrocarbon and main component of natural gas. A perfect example of tetrahedral molecular geometry (109.5° bond angles).',
        // Carbon at center, 4 hydrogens at tetrahedron vertices (C-H bond length 1.09 Å)
        atoms: [
            { position: [0, 0, 0], type: 'C', scale: 0.4 },
            { position: [0.629, 0.629, 0.629], type: 'H', scale: 0.3 },
            { position: [0.629, -0.629, -0.629], type: 'H', scale: 0.3 },
            { position: [-0.629, 0.629, -0.629], type: 'H', scale: 0.3 },
            { position: [-0.629, -0.629, 0.629], type: 'H', scale: 0.3 },
        ],
        bonds: [
            { start: [0, 0, 0], end: [0.629, 0.629, 0.629], type: 'covalent' },
            { start: [0, 0, 0], end: [0.629, -0.629, -0.629], type: 'covalent' },
            { start: [0, 0, 0], end: [-0.629, 0.629, -0.629], type: 'covalent' },
            { start: [0, 0, 0], end: [-0.629, -0.629, 0.629], type: 'covalent' },
        ]
    },
    ammonia: {
        id: 'ammonia',
        name: 'Ammonia',
        formula: 'NH₃',
        description: 'A pungent, colorless gas central to fertilizer production. Its trigonal pyramidal shape comes from a lone electron pair on nitrogen pushing the hydrogens together.',
        // Nitrogen above a triangle of 3 hydrogens (N-H bond length 1.01 Å, H-N-H angle ~107°)
        atoms: [
            { position: [0, 0, 0], type: 'N', scale: 0.42 },
            { position: [0.9375, 0, -0.3757], type: 'H', scale: 0.3 },
            { position: [-0.4688, 0.8119, -0.3757], type: 'H', scale: 0.3 },
            { position: [-0.4688, -0.8119, -0.3757], type: 'H', scale: 0.3 },
        ],
        bonds: [
            { start: [0, 0, 0], end: [0.9375, 0, -0.3757], type: 'covalent' },
            { start: [0, 0, 0], end: [-0.4688, 0.8119, -0.3757], type: 'covalent' },
            { start: [0, 0, 0], end: [-0.4688, -0.8119, -0.3757], type: 'covalent' },
        ]
    },
    carbon_dioxide: {
        id: 'carbon_dioxide',
        name: 'Carbon Dioxide',
        formula: 'CO₂',
        description: 'A linear molecule (180° bond angle) produced by respiration and combustion, and the primary greenhouse gas driving climate change.',
        atoms: [
            { position: [0, 0, 0], type: 'C', scale: 0.4 },
            { position: [1.16, 0, 0], type: 'O', scale: 0.45 },
            { position: [-1.16, 0, 0], type: 'O', scale: 0.45 },
        ],
        bonds: [
            { start: [0, 0, 0], end: [1.16, 0, 0], type: 'covalent' },
            { start: [0, 0, 0], end: [-1.16, 0, 0], type: 'covalent' },
        ]
    },
    benzene: (() => {
        const ringR = 1.39; // C-C aromatic bond length (Å)
        const hR = 2.48; // C-H bond extends radially outward
        const carbons: MoleculeAtom[] = [];
        const hydrogens: MoleculeAtom[] = [];
        const ringBonds: MoleculeBond[] = [];
        const chBonds: MoleculeBond[] = [];
        for (let i = 0; i < 6; i++) {
            const angle = (i / 6) * Math.PI * 2;
            const cPos: [number, number, number] = [ringR * Math.cos(angle), ringR * Math.sin(angle), 0];
            const hPos: [number, number, number] = [hR * Math.cos(angle), hR * Math.sin(angle), 0];
            carbons.push({ position: cPos, type: 'C', scale: 0.4 });
            hydrogens.push({ position: hPos, type: 'H', scale: 0.28 });
            chBonds.push({ start: cPos, end: hPos, type: 'covalent' });
        }
        for (let i = 0; i < 6; i++) {
            ringBonds.push({ start: carbons[i].position, end: carbons[(i + 1) % 6].position, type: 'covalent' });
        }
        return {
            id: 'benzene',
            name: 'Benzene',
            formula: 'C₆H₆',
            description: 'An aromatic ring of 6 carbons with delocalized electrons shared equally around the ring — the foundation of aromatic organic chemistry.',
            atoms: [...carbons, ...hydrogens],
            bonds: [...ringBonds, ...chBonds]
        };
    })(),
};

export const getMoleculeForElement = (symbol: string, activeId?: string | null): MoleculePreset | null => {
    // An explicit pick (e.g. from the Molecule Gallery or Academy exhibits) always wins,
    // regardless of which element happens to be selected.
    if (activeId && MOLECULE_PRESETS[activeId]) return MOLECULE_PRESETS[activeId];

    if (symbol === 'H' || symbol === 'O') return MOLECULE_PRESETS.water;
    if (symbol === 'Na' || symbol === 'Cl') return MOLECULE_PRESETS.nacl;
    if (symbol === 'Au') return MOLECULE_PRESETS.gold;
    if (symbol === 'S') return MOLECULE_PRESETS.penicillin;
    if (symbol === 'P') return MOLECULE_PRESETS.dna_segment;
    if (symbol === 'C') return MOLECULE_PRESETS.diamond; // Default carbon allotrope
    return null;
};
